---
title: "Tutorial2-ProperSpecificationofREmodels"
author: "Jared Knowles"
date: "Saturday, May 17, 2014"
output: html_document
---

<style>
p
{
max-width:550px;
}
</style>

```{r setup, echo=FALSE, error=FALSE, message=FALSE, eval=TRUE, results='hide'}
library(knitr)
opts_chunk$set(dev='svg', fig.width=6, fig.height=6, echo=TRUE, 
               message=FALSE, error=FALSE, warning=FALSE)

```


```{r loadandviewdata}
library(lme4) # load library
library(arm) # convenience functions for regression in R
lmm.data <- read.table("http://bayes.acs.unt.edu:8083/BayesContent/class/Jon/R_SC/Module9/lmm.data.txt",
                       header=TRUE, sep=",", na.strings="NA", dec=".", strip.white=TRUE)
#summary(lmm.data)
head(lmm.data)
```

## Fully Interacted Models

```{r fullinteract}

classEff <- lmList(extro ~ open + agree + social | class, data = lmm.data)
schoolEff <- lmList(extro ~ open + agree + social | school, data = lmm.data)



```

## Non-nested Classes

```{r lmer2}
MLexamp.7 <- lmer(extro ~ open + agree + social + (1|school) + (1|class), data=lmm.data)
display(MLexamp.7)
```

## Nested group effects

And finally, we can fit nested group effect terms through the following syntax:

```{r lmer3}
MLexamp.8 <- lmer(extro ~ open + agree + social + (1|school/class), data=lmm.data)
display(MLexamp.8)


```

Here the `(1|school/class)` says that we want to fit a mixed effect term for varying 
intercepts `1|` by schools, and for classes that are nested within schools. 


```{r}
MLexamp2 <- update(MLexamp1, .~ . + (1|class)) # add a intercept for class
MLexamp2 <- lmer(extro ~ open + agree + social + (1|class) + (1|school), 
                 data = lmm.data)
exactRLRT(m = MLexamp1, mA=MLexamp2, 
          m0 = )
```

## Non-correlated random effects

```{r lmer4}
MLexampUnCor <- lmer(extro ~ open + agree + social + (1|school/class) + (0 + open|school/class), 
                     data = lmm.data)
MLexampCor <- lmer(extro ~ open + agree + social + (1+open|school/class),
                     data = lmm.data)

VarCorr(MLexampUnCor)
VarCorr(MLexampCor)
```
